name: Dev Workflow

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build
        run: ./gradlew build
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/git @semantic-release/release-notes-generator conventional-changelog-conventionalcommits
      - name: Release
        env:
          GH_TOKEN: ${{ steps.create_token.outputs.token }}
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
        run: npx semantic-release

  docker-build-and-push:
    needs: release
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DEV_ECR_REPOSITORY_URL }}/repository/my-service
    steps:
      # ... (similar to your current docker build job)
      - name: Get version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}-${{ github.run_number }}
