name: Main Workflow

on:
  push:
    branches: [ main,prod ]
# Avoid running multiple pipelines concurrently to avoid overlapping releases and tags
concurrency:
  group: project
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # Bootstrap (no restore-keys) the Java cache and store it as -build-java
      - name: Set up the Java cache bringing Java artifacts
        uses: actions/cache@v3
        with:
          path: |
            build/
          key: build-${{ github.run_id }}
      - name: Build
        run: ./gradlew build
      - name: Archive Jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: 'build/libs/'
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Pull the Build cache bringing artifact from the upstream Build job
        uses: actions/cache@v3
        with:
          path: |
            build/
          key: build-${{ github.run_id }}
      - run: ls -l
      - run: ls -l build/
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/git @semantic-release/release-notes-generator @saithodev/semantic-release-backmerge
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release