name: Main Workflow

on:
  push:
    branches: [ main ]
# Avoid running multiple pipelines concurrently to avoid overlapping releases and tags
concurrency:
  group: project
  cancel-in-progress: false
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v2.1.4
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Git checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build and Test
        run: ./gradlew build
      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
      - run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/git @semantic-release/release-notes-generator conventional-changelog-conventionalcommits gradle-semantic-release-plugin
      - name: Create Maven settings
        run: |
          echo '<settings><servers><server>' > settings.xml
          echo "<id>github</id>" >> settings.xml
          echo "<username>${{ github.actor }}</username>" >> settings.xml
          echo "<password>${{ secrets.GITHUB_TOKEN }}</password>" >> settings.xml
          echo '</server></servers></settings>' >> settings.xml
      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: npx semantic-release
