on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
# Avoid running multiple pipelines concurrently to avoid overlapping releases
concurrency:
  group: prod-deploy
  cancel-in-progress: false

jobs:
  download-release-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: robinraju/release-downloader@v1.7
        with:
          tag: ${{ github.event.inputs.version }}
          fileName: '*.jar'
          out-file-path: 'build/libs'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sfat/release-gradle-plugins-playground:${{ github.event.inputs.version }}