on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
# Avoid running multiple pipelines concurrently to avoid overlapping releases
concurrency:
  group: prod-deploy
  cancel-in-progress: false

jobs:
  download-release-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.version }}
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v3
      - name: Build
        run: ./gradlew bootJar
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sfat/release-gradle-plugins-playground:${{ github.event.inputs.version }}
