name: Sync Dev with Main

on:
  release:
    types: [published]

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge main to dev
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout dev
          git merge origin/main
          git push origin dev
